### ISSUE TITLE
RISC0: PyTeal improvements

### ISSUE THREAD

**Issue by barnjamin** [barnjamin/zk-experiments#8]
https://github.com/algorand/pyteal/pull/624

https://github.com/algorand/pyteal/issues/496

**Comment by ahangsu** [comment]
Me retrospecting https://github.com/algorand/pyteal/issues/496 is that, it might be hard to improve it atm, for PyTeal introduces `TealType.any`, which makes it hard to push through the improvement.

Focusing on https://github.com/algorand/pyteal/issues/624 seems easier.
